#!/usr/bin/env bash
# Script: 1-types_of_network
# Description: Answers to questions about types of networks.

# What type of network a computer in local is connected to?
# 1. Internet
# 2. WAN
# 3. LAN
echo "3"

# What type of network could connect an office in one building to another office in a building a few streets away?
# 1. Internet
# 2. WAN
# 3. LAN
echo "2"

# What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?
# 1. Internet
# 2. WAN
# 3. LAN
echo "1"
