#!/usr/bin/env bash
# Script: 2-MAC_and_IP_address
# Description: Answers to questions about MAC and IP addresses.

# What is a MAC address?
# 1. The name of a network interface
# 2. The unique identifier of a network interface
# 3. A network interface
echo "2"

# What is an IP address?
# 1. Is to devices connected to a network what postal address is to houses
# 2. The unique identifier of a network interface
# 3. Is a number that network devices use to connect to networks
echo "3"
