#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 for all active IPv4 IPs.

# Install Nginx
apt-get update
apt-get install -y nginx

# Edit Nginx configuration
config_file="/etc/nginx/sites-available/default"
sed -i 's/listen [::]:80 default_server;/listen 80 default_server;/g' "$config_file"

# Restart Nginx
service nginx restart
