#!/bin/bash
# This script groups visitors by IP and HTTP status code and displays the data

# Use awk to group and count occurrences of IP and HTTP status code, then sort the data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
