#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter
counter=0

# Use a while loop to iterate while the counter is less than 10
while [ $counter -lt 10 ]; do
    echo "Best School"
    # Increment the counter
    ((counter++))
done
