#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize a counter
counter=0

# Use an until loop to iterate until the counter is greater than or equal to 10
until [ $counter -ge 10 ]; do
    echo "Best School"
    # Increment the counter
    ((counter++))
done
