#!/usr/bin/env bash
# This script configures the local host and facebook.com IP addresses
cp /etc/hosts ~/hosts.new; sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new; sed -i 's/facebook.com/8.8.8.8/' ~/hosts.new; sudo cp -f ~/hosts.new /etc/hosts; echo "IP addresses configured successfully!"
