#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user

# Update Nginx configuration to run as the nginx user
sed -i 's/user  nginx;/user  root;/g' /etc/nginx/nginx.conf

# Start Nginx on all active IPs and port 8080
nginx -g "daemon off;" -c /etc/nginx/nginx.conf
