#!/usr/bin/env bash
# SSH client configuration to use private key and refuse password authentication

# Specify the host for which this configuration applies
Host your_server_ip_or_hostname
  # Set the private key to be used
  IdentityFile ~/.ssh/school
  # Disable password authentication
  PasswordAuthentication no
